# Generated by Django 4.2.10 on 2024-02-17 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0002_alter_dailygoal_user_alter_dailygoal_weekly_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('goal_type', models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], max_length=1)),
                ('month', models.IntegerField(blank=True, help_text='Month as a number (1-12), for Monthly and Weekly goals', null=True)),
                ('week', models.IntegerField(blank=True, help_text='Week number in the year, for Weekly goals', null=True)),
                ('day', models.DateField(blank=True, help_text='Specific date for Daily goals', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='planner.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='monthlygoal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='monthlygoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weeklygoal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='weeklygoal',
            name='monthly_goal',
        ),
        migrations.RemoveField(
            model_name='weeklygoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='daily_goal',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.DateField(blank=True, help_text='Specific date for Daily goals', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='month',
            field=models.IntegerField(blank=True, help_text='Month as a number (1-12), for Monthly and Weekly goals', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='week',
            field=models.IntegerField(blank=True, help_text='Week number in the month, for Weekly goals', null=True),
        ),
        migrations.DeleteModel(
            name='DailyGoal',
        ),
        migrations.DeleteModel(
            name='MonthlyGoal',
        ),
        migrations.DeleteModel(
            name='WeeklyGoal',
        ),
    ]
